import type { Metadata } from "next";
import { Archivo, Inter, Sora, Hanken_Grotesk, Space_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import ScrollAnimations from "@/components/ScrollAnimations";

/* ---------------------------------------------------------------
   Self-hosted fonts via next/font (no render-blocking link, no CLS).
   Homepage:  Sora (display, --font-display) + Hanken Grotesk (body, --font-body).
   /admin + case study keep Inter + Archivo + Space Mono (via globals.css).
   --------------------------------------------------------------- */
const sora = Sora({ subsets: ["latin"], display: "swap", variable: "--font-display" });
const hanken = Hanken_Grotesk({ subsets: ["latin"], display: "swap", variable: "--font-body" });
const archivo = Archivo({ subsets: ["latin"], display: "swap", variable: "--font-archivo" });
const inter = Inter({ subsets: ["latin"], display: "swap", variable: "--font-inter" });
const mono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"], display: "swap", variable: "--font-mono" });

// If the custom domain isn't live yet, change this to "https://lakonos.vercel.app"
const SITE = "https://lakonos.com";
const TITLE = "Lakonos — Automate the work your people do by hand";
const DESCRIPTION =
  "Lakonos builds custom automation around how your business already works — replacing manual labour across warehouse, production, quality and admin.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: "Lakonos",
  keywords: [
    "business automation South Africa", "warehouse management system", "WMS", "ERP",
    "production planning", "WooCommerce automation", "custom software", "process automation",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: "Lakonos",
    url: SITE,
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_ZA",
    // og image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: { index: true, follow: true },
};

// Favicon: premium gradient orb on a dark rounded tile (inline SVG data URI)
const FAVICON =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' y1='0' x2='1' y2='1'%3E%3Cstop offset='0' stop-color='%23a5b4fc'/%3E%3Cstop offset='0.5' stop-color='%23d8b4fe'/%3E%3Cstop offset='1' stop-color='%2367e8f9'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect x='2' y='2' width='60' height='60' rx='14' fill='%230B0B14'/%3E%3Cpath d='M32 17 L18 49 M32 17 L46 49' stroke='url(%23g)' stroke-width='7' stroke-linecap='square' fill='none'/%3E%3C/svg%3E";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${hanken.variable} ${archivo.variable} ${inter.variable} ${mono.variable}`}
    >
      <head>
        <link rel="icon" type="image/svg+xml" href={FAVICON} />
      </head>
      <body>
        {children}
        <ScrollAnimations />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
